language: python
python: '2.7'
sudo: required
services:
  - docker
  - postgresql
addons:
  apt:
    update: true
  postgresql: "9.2"
  apt:
    packages:
      - postgresql-server-dev-9.2
jobs:
  include:
  - stage: test
    env: Type='virus scan'
    script:
      - sudo apt-get install clamav -y
      - sudo freshclam
      - clamscan --quiet -r ./
  - stage: test
    env: Type='unit tests'
    install:
      - cd chroma-manager
      - pip install -r requirements.txt
    before_script:
      - psql -c "CREATE USER chroma;" -U postgres
      - psql -c "ALTER USER chroma CREATEDB;" -U postgres
      - psql -c "CREATE DATABASE chroma OWNER chroma;" -U postgres
    script:
      - export IML_DISABLE_THREADS=1
      - python manage.py test tests/unit/
  - stage: test
    env: Type='behave tests'
    install:
      - cd chroma-manager
      - pip install -r requirements.txt
    script:
      - export IML_DISABLE_THREADS=1
      - behave --format plain tests/feature/cli/features