language: python
python: '2.7'
sudo: required
services:
  - docker
  - postgres
addons:
  apt:
    update: true
  postgresql: "9.2"
jobs:
  include:
  - stage: test
    env: Type='virus scan'
    script:
      - sudo apt-get install clamav -y
      - sudo freshclam
      - clamscan --quiet -r ./
  - stage: test
    env: Type='module test'
    install:
      - cd chroma-manager
      - pip install -r requirements.txt
    before_script:
      - psql -c "CREATE USER chroma;" -U postgres
      - psql -c "CREATE DATABASE chroma OWNER chroma;" -U postgres
    script:
      - nosetests